//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neuronic.Filters.Testing.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Neuronic.Filters.Testing.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1	2	1	1	-1,34666548227894	0,454665597732817
        ///1	2	1	1	-1,37216276258226	0,482207713411182
        ///1	2	1	1	-1,42425781942110	0,538480698790711
        ///1	2	1	1	-1,50506719962617	0,625770843897491
        ///1	2	1	1	-1,61746385201619	0,747181502805462
        ///1	2	1	1	-1,76442917077017	0,905933172068909.
        /// </summary>
        internal static string LowPass12 {
            get {
                return ResourceManager.GetString("LowPass12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1	2	1	1	-1,88341013175015	0,886839485733753
        ///1	2	1	1	-1,88751424372354	0,890951070563162
        ///1	2	1	1	-1,89561692603954	0,899068506418721
        ///1	2	1	1	-1,90750478153630	0,910978007580391
        ///1	2	1	1	-1,92285253991200	0,926353711487149
        ///1	2	1	1	-1,94121856331170	0,944753176140269
        ///1	2	1	1	-1,96204170972559	0,965614237790415
        ///1	2	1	1	-1,98464193005427	0,988255609090035.
        /// </summary>
        internal static string LowPass16 {
            get {
                return ResourceManager.GetString("LowPass16", resourceCulture);
            }
        }
    }
}
