//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neuronic.Filters.Testing.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Neuronic.Filters.Testing.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1	-1,99493209406861	1	1	-1,99351850852093	0,998602649152472
        ///1	-1,99493209406861	1	1	-1,99356339360702	0,998608073710361
        ///1	-1,99493209406861	1	1	-1,99368959093240	0,998811007929520
        ///1	-1,99493209406861	1	1	-1,99381508134623	0,998824106395447
        ///1	-1,99493209406861	1	1	-1,99405248147615	0,999203210535372
        ///1	-1,99493209406861	1	1	-1,99423384046735	0,999216313638093
        ///1	-1,99493209406861	1	1	-1,99455227161735	0,999719719161690
        ///1	-1,99493209406861	1	1	-1,99475624937562	0,999725149280838.
        /// </summary>
        internal static string BandStop08 {
            get {
                return ResourceManager.GetString("BandStop08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1	-2	1	1	-1,86480445083537	0,869542256160129
        ///1	-2	1	1	-1,88350864178159	0,888293967807734
        ///1	-2	1	1	-1,91907529383978	0,923950982087784
        ///1	-2	1	1	-1,96762058043629	0,972619605003675.
        /// </summary>
        internal static string HighPass08 {
            get {
                return ResourceManager.GetString("HighPass08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1	-2	1	1	-1,99611032558779	0,996114173407759
        ///1	-2	1	1	-1,99637465823022	0,996378506559731
        ///1	-2	1	1	-1,99688550799202	0,996889357306273
        ///1	-2	1	1	-1,99760840512342	0,997612255831174
        ///1	-2	1	1	-1,99849448305329	0,998498335469104
        ///1	-2	1	1	-1,99948370234585	0,999487556668544.
        /// </summary>
        internal static string HighPass12 {
            get {
                return ResourceManager.GetString("HighPass12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1	-2	1	1	-1,96037388726628	0,960770176707166
        ///1	-2	1	1	-1,96185271232904	0,962249300714299
        ///1	-2	1	1	-1,96476002232263	0,965157198420402
        ///1	-2	1	1	-1,96899615073797	0,969394183168790
        ///1	-2	1	1	-1,97441421193665	0,974813339628162
        ///1	-2	1	1	-1,98082344680450	0,981223870122376
        ///1	-2	1	1	-1,98799398823124	0,988395861073551
        ///1	-2	1	1	-1,99566322293089	0,996066646108449.
        /// </summary>
        internal static string HighPass16 {
            get {
                return ResourceManager.GetString("HighPass16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1	2	1	1	-1,34666548227894	0,454665597732817
        ///1	2	1	1	-1,37216276258226	0,482207713411182
        ///1	2	1	1	-1,42425781942110	0,538480698790711
        ///1	2	1	1	-1,50506719962617	0,625770843897491
        ///1	2	1	1	-1,61746385201619	0,747181502805462
        ///1	2	1	1	-1,76442917077017	0,905933172068909.
        /// </summary>
        internal static string LowPass12 {
            get {
                return ResourceManager.GetString("LowPass12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1	2	1	1	-1,88341013175015	0,886839485733753
        ///1	2	1	1	-1,88751424372354	0,890951070563162
        ///1	2	1	1	-1,89561692603954	0,899068506418721
        ///1	2	1	1	-1,90750478153630	0,910978007580391
        ///1	2	1	1	-1,92285253991200	0,926353711487149
        ///1	2	1	1	-1,94121856331170	0,944753176140269
        ///1	2	1	1	-1,96204170972559	0,965614237790415
        ///1	2	1	1	-1,98464193005427	0,988255609090035.
        /// </summary>
        internal static string LowPass16 {
            get {
                return ResourceManager.GetString("LowPass16", resourceCulture);
            }
        }
    }
}
